name: agents_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - aiofiles=24.1.0=py313haa95532_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.13.2=py313h4f5f683_0
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - altair=6.0.0=pyhd8ed1ab_1
  - annotated-doc=0.0.4=py313haa95532_0
  - annotated-types=0.6.0=py313haa95532_1
  - anyio=4.10.0=py313haa95532_0
  - aom=3.12.1=h00a0c3c_0
  - asttokens=3.0.1=pyhd8ed1ab_0
  - attrs=25.4.0=pyh71513ae_0
  - audioop-lts=0.2.2=py313h827c3e9_0
  - blas=1.0=mkl
  - bottleneck=1.4.2=py313h540bb41_1
  - brotli=1.2.0=h17ff524_0
  - brotli-bin=1.2.0=h6910e44_0
  - brotli-python=1.2.0=py313hd3493e3_0
  - brotlicffi=1.1.0.0=py313h885b0b7_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=he9e932c_0
  - certifi=2025.11.12=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_1
  - charset-normalizer=3.4.4=py313haa95532_0
  - click=8.2.1=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py313hf069bd2_3
  - cpython=3.13.9=py313hd8ed1ab_101
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.17=py313h927ade5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h9214b88_0
  - fastapi=0.121.1=py313hdf80283_0
  - ffmpeg=6.1.1=haa678a1_5
  - ffmpy=0.3.0=py313h0789b6b_0
  - filelock=3.20.0=py313haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py313hd650c13_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.7.0=py313h0c48a3b_0
  - fsspec=2025.10.0=py313h4442805_0
  - gradio-client=1.13.3=py313haa95532_0
  - graphite2=1.3.14=hd77b12b_1
  - groovy-python=0.1.2=py313haa95532_0
  - h11=0.16.0=py313haa95532_1
  - harfbuzz=10.2.0=he2f9f60_1
  - hf-xet=1.1.8=py313h79d111c_0
  - httpcore=1.0.9=py313haa95532_0
  - httpx=0.28.1=py313haa95532_1
  - huggingface_hub=0.34.4=py313haa95532_0
  - icu=73.1=h6c2663c_0
  - idna=3.11=py313haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.7.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=py313haa95532_0
  - jpeg=9f=ha349fce_0
  - jsonschema=4.25.1=pyhe01879c_0
  - jsonschema-specifications=2025.9.1=pyhcf101f3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py313h1a38498_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libavif=1.1.1=h952b276_1
  - libbrotlicommon=1.2.0=hc82b238_0
  - libbrotlidec=1.2.0=h431afc6_0
  - libbrotlienc=1.2.0=ha521d6b_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.13.3=h57928b3_1
  - libfreetype6=2.13.3=h0b5ce68_1
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libmpdec=4.0.0=h827c3e9_0
  - libogg=1.3.5=h2bbff1b_1
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=hc70643c_0
  - libtheora=1.2.0=habf309d_1
  - libtiff=4.7.0=h404307b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=4.0.0=py313haa95532_0
  - matplotlib-base=3.10.6=py313he1ded55_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=py313haa95532_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=2.1.1=py313hbc2a22c_0
  - mkl_random=1.3.0=py313h42c1672_0
  - multidict=6.6.3=py313hd650c13_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - narwhals=2.12.0=pyhcf101f3_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.14.1=py313h7660c64_0
  - numpy=2.3.4=py313h050da96_1
  - numpy-base=2.3.4=py313h1e017a8_1
  - openjdk=21.0.6=h5da7b33_0
  - openjpeg=2.5.4=h56d5a42_1
  - openssl=3.6.0=h725018a_0
  - orjson=3.11.4=py313h114bc41_0
  - packaging=25.0=py313haa95532_1
  - pandas=2.3.3=py313h42c1672_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h5740b90_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py313hb4c8b1a_0
  - psutil=7.1.3=py313h5fd188c_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.23=py313haa95532_0
  - pycryptodome=3.23.0=py313h5ea7bf4_1
  - pydantic=2.11.9=py313haa95532_0
  - pydantic-core=2.33.2=py313h215eeae_0
  - pydub=0.25.1=py313haa95532_0
  - pygments=2.19.2=py313haa95532_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=py313haa95532_1
  - python=3.13.9=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-gil=3.13.9=h4df99d1_101
  - python-multipart=0.0.20=py313haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313haa95532_0
  - pywin32=311=py313h40c08fc_1
  - pyyaml=6.0.3=py313hb9a58be_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - qhull=2020.2=hc790b64_5
  - qtbase=6.9.2=h06bae2a_5
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - referencing=0.37.0=pyhcf101f3_0
  - requests=2.32.5=py313haa95532_1
  - rich=14.2.0=py313haa95532_0
  - rpds-py=0.29.0=py313hfbe8231_0
  - ruff=0.12.0=py313h1361809_0
  - safehttpx=0.1.7=py313haa95532_0
  - semantic_version=2.10.0=py313haa95532_0
  - setuptools=80.9.0=py313haa95532_0
  - shellingham=1.5.4=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - sniffio=1.3.0=py313haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - starlette=0.47.3=py313haa95532_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - tomlkit=0.13.3=py313haa95532_0
  - tornado=6.5.2=py313h5ea7bf4_2
  - tqdm=4.67.1=py313h4442805_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.17.4=py313haa95532_0
  - typing-extensions=4.15.0=py313haa95532_0
  - typing-inspection=0.4.2=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - uvicorn=0.35.0=py313haa95532_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - websockets=15.0.1=py313h827c3e9_0
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.22.0=py313hd650c13_0
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - gradio==5.49.1
      - h2o==3.46.0.8
      - huggingface-hub==0.36.0
      - markupsafe==3.0.3
      - pillow==11.3.0
      - python-dotenv==1.2.1
      - smolagents==1.23.0
      - tabulate==0.9.0
prefix: C:\Users\lixia\miniconda3\envs\agents_env
